### ISSUE TITLE
Dashboard No Login

### ISSUE THREAD

**Issue by sergimicoortiz** [JuanLuisLopez-code/VueJS_Laravel_Spring-Boot_MySQL#16]
- [x] Make the dashboard without login
- [x] CRUD categories
- [x] CRUD mesas

**Comment by JuanLuisLopez-code** [comment]
CRUD mesas: 

- [ ] HTML & CSS
- [ ] Enable Search depends of store

**Comment by JuanLuisLopez-code** [comment]
- [ ] Add categories on CRUD of mesa
