### ISSUE TITLE
Filters Spring Vue

### ISSUE THREAD

**Issue by sergimicoortiz** [JuanLuisLopez-code/VueJS_Laravel_Spring-Boot_MySQL#22]
- [x] Filters frontend component
- [x] Filters Spring-Boot

**Comment by JuanLuisLopez-code** [comment]
- [ ] Filter Only categories
- [ ] Filter Only capacity
- [ ] Filter Only order  ASC or DESC
- [ ] Filter Categories with capacity
- [ ] Filter Categories ordered
- [ ] Filter Categories, capacity and order
- [ ] Filter Capacity ordered
